### ISSUE TITLE
Size limit for encryption

### ISSUE THREAD

**Issue by jnigri** [aws/c3r#234]
Hello,

I would like to use c3r with very large files (~ >50GiB files with >1B rows).
It seems to fail once it reached almost 8 million rows:
```
...
[INFO]: 7600000 rows loaded.
[INFO]: 7700000 rows loaded.
[INFO]: 7800000 rows loaded.
[INFO]: 7900000 rows loaded.
[ERROR]: An error occurred: Error accessing the SQL database.
```

I'm using `c3r-cli-1.2.0.jar`.
I tried to change the maximum heap size of the JVM but it didn't seem to have an effect.

Is that a known limitation of c3r?

**Comment by Snidd111** [comment]
Hey @jnigri,

Thanks for reaching out. That is not an expected behavior for C3R. We'd like to get some additional feedback to try and reproduce it locally if possible.

Regarding the 50GiB input files, could you elaborate on the shape of the data? For example, approximately how many columns are there in total? How many target columns are cleartext, fingerprint, and sealed respectively?

Did C3R fail on the same batch or same line each time it ran? Or are you observing this same failure on different datasets?

Regarding computational resources, is it possible you're running out of physical hard disk memory while C3R is running? (C3R uses temporary files for storage which can consume space throughout encryption and data processing.)

Have you tried running in verbose mode (see the --enableStackTraces flag) to see if you get a more specific error message? Note: verbose mode causes additional debugging information to be logged, so ensure terminal and execution logs are scrubbed if necessary from your environment.

**Comment by jnigri** [comment]
Hi @Snidd111,

Thanks for the quick response.


> (C3R uses temporary files for storage which can consume space throughout encryption and data processing.)

That was it!  
On my setup my `/tmp` is on a partition with a limited amount of space. I was able to fix my issue using `-Djava.io.tmpdir=<other path>`

Many thanks.

**Comment by jnigri** [comment]
Ah,

Re-opening the ticket, got a bit too excited. Looks like I'm having another issue:


```
...
[INFO]: 999800000 rows loaded.
[INFO]: 999900000 rows loaded.
[INFO]: 1000000000 rows loaded.
[ERROR]: An error occurred: An SQL exception occurred during marshalling.
[WARN]: Output files may have been left on disk.
```


I've generated the data using the following script:

*script.pl*
```
#!/usr/bin/perl
use strict;
use warnings;
use Digest::SHA qw(sha256_hex);
use Text::CSV;

my $num_lines = $ARGV[0] || die "Number of lines is required.\n";

my $csv = Text::CSV->new ( { binary => 1, eol => $/ } );

for (my $i=1; $i<=$num_lines; $i++) {
    my @line;
    push @line, sha256_hex("$i");

    $csv->print (*STDOUT, \@line);
}
```

*usage:*
```
chmod +x script.pl
./script.pl 1000000000
```

**Comment by Snidd111** [comment]
Hey @jnigri,

Thanks for the script. That will help us simulate the problem. Since this is purely generated data and I'm assuming not sensitive (please correct me if I'm wrong), would you mind sharing the schema you're using to run the encryption as well?

If you run the encryption with the added parameter `--enableStackTraces`, is the error more useful?

**Comment by jnigri** [comment]
Hi,

Yes I'm using generated data to get familiar with C3R and AWS Clean Room. Here is the schema:

```
{
  "columns": [
    {
      "type": "fingerprint",
      "sourceHeader": "hash",
      "targetHeader": "hash_fingerprint"
    }
  ],
  "headerRow": false
}
```

I was able to run it with `--enableStackTraces`, I got this:
```
[ERROR]: An error occurred: An SQL exception occurred during marshalling.
com.amazonaws.c3r.exception.C3rRuntimeException: An SQL exception occurred during marshalling.
	at com.amazonaws.c3r.action.RowMarshaller.checkForInvalidDuplicates(RowMarshaller.java:354)
	at com.amazonaws.c3r.action.RowMarshaller.loadInput(RowMarshaller.java:275)
	at com.amazonaws.c3r.action.RowMarshaller.marshal(RowMarshaller.java:196)
	at com.amazonaws.c3r.cli.EncryptMode.call(EncryptMode.java:335)
	at com.amazonaws.c3r.cli.EncryptMode.call(EncryptMode.java:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.amazonaws.c3r.cli.Main.main(Main.java:85)
Caused by: org.sqlite.SQLiteException: [SQLITE_FULL] Insertion failed because database is full (database or disk is full)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.execute(DB.java:988)
	at org.sqlite.core.CoreStatement.exec(CoreStatement.java:79)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$executeQuery$1(JDBC3Statement.java:83)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:79)
	at com.amazonaws.c3r.action.RowMarshaller.checkForInvalidDuplicates(RowMarshaller.java:347)
	... 13 more
```

I think it's pretty clear that SQLLITE doesn't have enough space. It's probably linked to my setup where only my partition `/home` has enough space available for this scale of data.

I'm going to retry using the var env `SQLITE_TMPDIR` to set it up to my `/home` partition. From what it's described [here](https://www.sqlite.org/tempfiles.html) I believe it should help.
I'll put an update here once it's done.

**Comment by Snidd111** [comment]
Thanks for sharing. That is interesting that SQLLite is failing like that. 

To continue testing that you have enough space, you can change where SQLLite is writing its temporary table during runtime by using the `--tempDir` command for C3R.

**Comment by jnigri** [comment]
I confirm it works on my setup using `SQLITE_TMPDIR`.

Thanks for the help.
